### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OpTriumph**
add gif

### CODE REVIEW

**Comment by OpTriumph** [comment]
Is there any part that I can add in README? @L-SuMin

**Comment by OpTriumph** [comment]
@L-SuMin Oh never mind. The youtube video demo is much more better!
Very impressive work from start to end

**Comment by L-SuMin** [comment]
Oh... sorry. I was working on report and wiki.
You was a good teammate too!

**Comment by OpTriumph** [comment]
@L-SuMin 
I’m sorry that I wasn’t able to do much at this final stage. Only wish I can do more and help to build the project.
you guys are amazing, truly.

**Pull request closed without merging**
