### PR TITLE
can load, add tweet; page, component modified

### PR DESCRIPTION
**Pull request by OpTriumph**
Load 가능하고, add tweet 가능하고 
Home page, Twit , TwitDialog에  이부분 내용을 구현했습니다

### CODE REVIEW

**Comment by OpTriumph** [comment]
@L-SuMin

**Comment by L-SuMin** [comment]
OH... I made all possible part(load, add, delete) and some modified some button actions.
I'll make PR, so see them

**Comment by OpTriumph** [comment]
@L-SuMin what can i do on top of your current work??

**Comment by L-SuMin** [comment]
If you don't mind, please make add comment part

**Comment by OpTriumph** [comment]
@L-SuMin 
Of course. I will try my best to implement it and  PR
If you have updates , please upload and PR!

**Pull request closed without merging**
