### PR TITLE
install dotenv

### PR DESCRIPTION
**Pull request by JeongJuRyu**

### CODE REVIEW

**Comment by OpTriumph** [comment]
also need to install cookie-parser and passport-local

**Comment by OpTriumph** [comment]
Countered this error

[nodemon] starting `node app.js`
Running Server..
ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:116:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ConnectionManager._connect (H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:318:24)
    at async H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:250:32
    at async ConnectionManager.getConnection (H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:280:7)
    at async H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\sequelize.js:613:26
    at async MySQLQueryInterface.createTable (H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\dialects\abstract\query-interface.js:225:12)
    at async Function.sync (H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\model.js:1300:5)
    at async Sequelize.sync (H:\Master\MiniTwitter-master\back\node_modules\sequelize\lib\sequelize.js:793:35) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}

**Comment by JeongJuRyu** [comment]
지금 뜨는 오류는  MySQL이랑 node가 연결이 안 되서 그런건데, 저는  연결이 되어서 무리없이 되는데 지양님은  설치되어 있지 않아서 생기는 오류같습니다.. 이게 테스트를 하려면 MySQL을 설치 하셔야 되거나, 아님 다른 방법을 찾아봐야 될 것 같아요..ㅠ

**Comment by OpTriumph** [comment]
네, 알겠습니다!

**Pull request closed without merging**
