### PR TITLE
Component

### PR DESCRIPTION
**Pull request by OpTriumph**

### CODE REVIEW

**Comment by OpTriumph** [comment]
참고용으로 하세요

Updated sagas and reducers
Tested with Typicode Fake JSON db.: 
    1.can fetch user info and show in the profile component
   2. fetech all the tweets
   3.  can add tweets
   
<a href="https://ibb.co/vsYgXqh">Screenshot-1102</a>

<a href="https://ibb.co/svpK8rq">Screenshot-1105</a>
 <a href="https://ibb.co/v3QQjGT">Screenshot-1106</a>

**Comment by OpTriumph** [comment]
Dont know why the conflict happens. but can resolve in github

**Comment by OpTriumph** [comment]
Using typicode Fake JSON db, it can store the db files in the project folder even with rebooting db

**Comment by L-SuMin** [comment]
Try is impressive.
While we are doing with back end server,  please try and commit codes using backend server instead fake DB.
We don't have enough time to replace.

**Comment by OpTriumph** [comment]
Because Im too unfamiliar with backend, I'm afraid I won't be able to help too much on that...
If there's unimplemented frontend part with the context of only having a working backend part
please push to a branch, I will work as fast as I can on that

**Comment by L-SuMin** [comment]
I thought that you could catch up because redux and saga codes are very similar to implemented code.
Well... Then I'll make remain parts of redux and saga. next, you use them in the proper part of the frontend code.
If you agree with it, please write a comment and take a sleep.
I will make PR with the completed redux and saga before 9:00

**Comment by OpTriumph** [comment]
@L-SuMin 
Hi, I'm in a situation where I can construct the frontend part If the api calls works
Currently The backend router on posts doesn't seems to work because when I make POST calls, it says 404,
that's why I used fake db because I can see the redux and saga code result right away

**Comment by OpTriumph** [comment]
@L-SuMin I can make some part of the redux and sagas code with you If you insists to make them, Maybe that will speed up the process. 
I can sleep less, no problem on that.

**Comment by OpTriumph** [comment]
@L-SuMin 
Now I'm using the backend code that is on the backend Branch,
if the post router is indeed be able to add posts with no error, please let me know.
Or is there the newer version of backend code so I can work on them?

**Comment by OpTriumph** [comment]
@L-SuMin 
When I try to fetch the posts , here is the error on the console
GET http://localhost:3065/posts/ 404 (Not Found)

Is the router working on your side?

**Comment by L-SuMin** [comment]
If your problem is only on GET http://localhost:3065/posts, one line in back/app.js is wrong
`const postsRouter = require("./routes/post");`
should changes to 
`const postsRouter = require("./routes/posts");`
I hope that all your problem solved...

**Pull request closed without merging**
